---
title: "Crt modeling code"
author: "Molly"
date: "July 24, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### loading necessary libraries and uploading data
library(lme4)

#reading data 
ind_full <- read.csv("~/Desktop/Loved Children/LC MLM/LC_merged.csv")
```

```{r}
######### preliminary tables ### 

table(ind_full$year)

mixed <- table(ind_full$mixed, ind_full$year)
prop.table(mixed, margin = 2)
chisq.test(mixed)

###### chi squared tests #########

crt_mut <- table(ind_full$CRT, ind_full$year)
crt_mut
prop.table(crt_mut, margin =2)
print("the proportion of CRT mutations remains steady, 58% in 2007 and 54% in 2013")

### the function for confidence intervals #### 
conint <- function(n, p, z=1.96, cc=TRUE){
  out <- list()
  if(cc){
    out$lb <- p - z*sqrt((p*(1-p))/n) - 0.5/n
    out$ub <- p + z*sqrt((p*(1-p))/n) + 0.5/n
  } else {
    out$lb <- p - z*sqrt((p*(1-p))/n)
    out$ub <- p + z*sqrt((p*(1-p))/n)
  }
  out
}

conint(n = 162, p = 0.580, z = 1.96, cc = F)
conint(n = 513, p = 0.536, z = 1.96, cc = F)

### monoclonal infections only 

crt_mono <- subset(ind_full, ind_full$mixed == 0)

mono_crt <- table(crt_mono$CRT, crt_mono$year)
mono_crt
prop.table(mono_crt, margin = 2)
chisq.test(mono_crt)

conint(n = 125, p = 0.456, z = 1.96, cc = F)
conint(n = 398, p = 0.536, z = 1.96, cc = F)

```

```{r}
####### CRT ########
### running poisson model with weights 

CRT_1 <- glmer(CRT  ~ PrevPct10 + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weights = ind_full$weight)
summary(CRT_1)

CRT_2 <- glmer(CRT  ~ Chlor10 + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weights = ind_full$weight)
summary(CRT_2)

CRT_3 <- glmer(CRT  ~ wealthindex 
               + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weights = ind_full$weight)
summary(CRT_3)

CRT_4 <- glmer(CRT  ~ wealth_mean 
               + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weights = ind_full$weight)
summary(CRT_4)

CRT_5 <- glmer(CRT  ~ mixed 
               + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weights = ind_full$weight)
summary(CRT_5)

CRT_6 <- glmer(CRT  ~ pctedu0 
               + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weight = ind_full$weight)
summary(CRT_6)

CRT_6_test <- glmer(CRT  ~ pctedu0 
               + (1|province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weight = ind_full$weight)
# removing the random effect for year to see if it converges 
summary(CRT_6_test)

CRT_7 <- glmer(CRT  ~ urban1rural0 
               + (1|year/province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weight = ind_full$weight)
summary(CRT_7)

CRT_8 <- glmer(CRT  ~ total 
               + (1|province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weight = ind_full$weight)
summary(CRT_8)

CRT_8_test <- glmer(CRT  ~ weighted_total 
               + (1|province), 
               data = ind_full, 
               family=poisson(link = "log"),
               weight = ind_full$weight)
summary(CRT_8_test)
```

